# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Baltimore’s Civil Rights Heritage
tagline:             'Looking for Landmarks from the Movement'
description:         'This site is a repository for writing, data and resources related to the African-American Civil Rights movement in Baltimore. This is a project of <a href="http://baltimoreheritage.org/">Baltimore Heritage</a> and our partners.'
url:                 http://baltimoreheritage.github.io/baltimore-civil-rights-heritage
baseurl:             '/baltimore-civil-rights-heritage'
paginate:            5

# About/contact
author:
  name:              Baltimore Heritage
  url:               https://baltimoreheritage.org
  email:             info@baltimoreheritage.org
