# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

markdown: Pandoc

# Setup
title:               Baltimore’s Civil Rights Heritage
tagline:             'Looking for Landmarks from the Movement'
description:         'This site is a repository for writing, data and resources related to the African-American Civil Rights movement in Baltimore. This is a project of <a href="http://baltimoreheritage.org/">Baltimore Heritage</a> and our partners.'
url:                 https://baltimoreheritage.github.io/civil-rights-heritage
baseurl:             '/civil-rights-heritage'
paginate:            5

# About/contact
author:
  name:              Baltimore Heritage
  url:               http://baltimoreheritage.org
  email:             info@baltimoreheritage.org

# Google Analytics

google_analytics: UA-16215864-7

# Required Gems

gems:
  - jekyll-pandoc
  - jekyll-paginate

exclude:
  - README.md
  - Rakefile
  - vendor
  - Gemfile
  - Gemfile.lock
  - .travis.yml

pandoc:
  extensions:
    - normalize
    - smart
    - csl: _styles/chicago-note-bibliography.csl
    - bibliography: bibliography/references.bib
